export default function KnowledgePage() {
  return (
    <main style={{ minHeight: "100vh", background: "var(--bg)", color: "var(--text)" }}>

      {/* ── Nav ── */}
      <nav style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0 48px", height: "56px",
        background: "rgba(7,8,12,0.88)", backdropFilter: "blur(12px)",
        borderBottom: "1px solid var(--border)",
      }}>
        <a href="/" style={{ fontFamily: "Georgia, serif", fontSize: "15px", color: "var(--gold)", fontStyle: "italic", textDecoration: "none" }}>
          AI Agent Army
        </a>
        <div style={{ display: "flex", alignItems: "center", gap: "32px" }}>
          <a href="/agents" style={{ fontSize: "12px", color: "var(--muted)", letterSpacing: "0.1em", textDecoration: "none" }}>Agents</a>
          <a href="/knowledge" style={{ fontSize: "12px", color: "var(--text)", letterSpacing: "0.1em", textDecoration: "none", opacity: 1 }}>Knowledge</a>
        </div>
      </nav>

      {/* ── Header ── */}
      <section style={{ padding: "140px 48px 80px", maxWidth: "800px", margin: "0 auto" }}>
        <p style={{
          fontSize: "11px", fontWeight: 700, color: "var(--gold)",
          letterSpacing: "0.24em", textTransform: "uppercase", marginBottom: "16px",
        }}>
          Content Pod
        </p>
        <h1 style={{
          fontFamily: "Georgia, serif", fontSize: "clamp(32px, 5vw, 56px)",
          fontWeight: 400, lineHeight: 1.1, marginBottom: "20px", color: "var(--text)",
        }}>
          Knowledge base.
        </h1>
        <p style={{ fontSize: "18px", color: "var(--muted)", lineHeight: 1.7, fontWeight: 300 }}>
          Articles generated by the Content Agent. Create a content brief in Linear under the Content Pod — the agent writes, opens a PR, and publishes here.
        </p>
      </section>

      {/* ── Empty state ── */}
      <section style={{ padding: "0 48px 120px", maxWidth: "800px", margin: "0 auto" }}>
        <div style={{
          border: "1px dashed var(--border)", borderRadius: "12px",
          padding: "80px 48px", textAlign: "center",
        }}>
          <p style={{
            fontFamily: "Georgia, serif", fontSize: "32px", fontStyle: "italic",
            color: "var(--gold)", opacity: 0.3, marginBottom: "20px",
          }}>
            No articles yet.
          </p>
          <p style={{ fontSize: "14px", color: "var(--muted)", lineHeight: 1.7, maxWidth: "400px", margin: "0 auto" }}>
            Assign a Linear card to the Content Agent to generate the first article. It will appear here after the PR merges.
          </p>
        </div>
      </section>

    </main>
  );
}
