// Individual knowledge base articles are generated by the content-agent.
// Each article is a standalone page at app/knowledge/[slug]/page.tsx.

export default function ArticlePage() {
  return (
    <main style={{ minHeight: "100vh", background: "var(--bg)", color: "var(--text)" }}>
      <nav style={{
        position: "fixed", top: 0, left: 0, right: 0, zIndex: 50,
        display: "flex", alignItems: "center", justifyContent: "space-between",
        padding: "0 48px", height: "56px",
        background: "rgba(7,8,12,0.88)", backdropFilter: "blur(12px)",
        borderBottom: "1px solid var(--border)",
      }}>
        <a href="/" style={{ fontFamily: "Georgia, serif", fontSize: "15px", color: "var(--gold)", fontStyle: "italic", textDecoration: "none" }}>
          AI Agent Army
        </a>
        <div style={{ display: "flex", alignItems: "center", gap: "32px" }}>
          <a href="/agents" style={{ fontSize: "12px", color: "var(--muted)", letterSpacing: "0.1em", textDecoration: "none" }}>Agents</a>
          <a href="/knowledge" style={{ fontSize: "12px", color: "var(--text)", letterSpacing: "0.1em", textDecoration: "none" }}>Knowledge</a>
        </div>
      </nav>
      <article style={{ padding: "140px 48px 120px", maxWidth: "740px", margin: "0 auto" }}>
        <a href="/knowledge" style={{ fontSize: "12px", color: "var(--muted)", textDecoration: "none", letterSpacing: "0.1em", display: "block", marginBottom: "48px" }}>
          ← Knowledge base
        </a>
        <p style={{ fontSize: "14px", color: "var(--muted)", marginBottom: "40px" }}>
          This article will be generated by the Content Agent.
        </p>
      </article>
    </main>
  );
}
